title:              Hare Krishna Japan
email:              nitaigourtokyo@gmail.com
description:        マントラヨガ、バガヴァッドギーター、バクテｲヨガ
author:             Start Bootstrap
baseurl:            "/"
url:                "https://www.harekrishna.jp"

# Social Profiles
twitter_username:   TokyoKrishna
github_username:    
facebook_username:  HareKrishnaTokyo
instagram_username:  harekrishnatokyo
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
